"""add user.section_id for class rosters

Revision ID: 1d61da8d89e7
Revises: e02c190425d7
Create Date: 2026-06-24 22:14:03.200163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d61da8d89e7'
down_revision: Union[str, Sequence[str], None] = 'e02c190425d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_section_id'), 'users', ['section_id'], unique=False)
    op.create_foreign_key(None, 'users', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_section_id'), table_name='users')
    op.drop_column('users', 'section_id')
    # ### end Alembic commands ###
