"""doubt forum (doubts, answers, votes)

Revision ID: 6442c17bd684
Revises: 7f8fd7316529
Create Date: 2026-06-26 19:53:16.235821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6442c17bd684'
down_revision: Union[str, Sequence[str], None] = '7f8fd7316529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
