"""face_enrollments table

Revision ID: 795c75ccfdc3
Revises: d1a4a0794348
Create Date: 2026-06-26 11:30:13.326453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795c75ccfdc3'
down_revision: Union[str, Sequence[str], None] = 'd1a4a0794348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_enrollments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_by_id', sa.Integer(), nullable=True),
    sa.Column('det_score', sa.Float(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrolled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_enrollments')
    # ### end Alembic commands ###
