"""doubt forum (doubts, answers, votes)

Revision ID: 7f8fd7316529
Revises: f8bdcd852728
Create Date: 2026-06-26 19:48:18.621252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8fd7316529'
down_revision: Union[str, Sequence[str], None] = 'f8bdcd852728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='doubt_status'), nullable=False),
    sa.Column('asked_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubts_asked_by_id'), 'doubts', ['asked_by_id'], unique=False)
    op.create_index(op.f('ix_doubts_section_id'), 'doubts', ['section_id'], unique=False)
    op.create_index(op.f('ix_doubts_status'), 'doubts', ['status'], unique=False)
    op.create_index(op.f('ix_doubts_subject_id'), 'doubts', ['subject_id'], unique=False)
    op.create_table('doubt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doubt_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('answered_by_id', sa.Integer(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doubt_id'], ['doubts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubt_answers_answered_by_id'), 'doubt_answers', ['answered_by_id'], unique=False)
    op.create_index(op.f('ix_doubt_answers_doubt_id'), 'doubt_answers', ['doubt_id'], unique=False)
    op.create_table('answer_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['doubt_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'user_id', name='uq_answer_vote_user')
    )
    op.create_index(op.f('ix_answer_votes_answer_id'), 'answer_votes', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_votes_user_id'), 'answer_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_votes_user_id'), table_name='answer_votes')
    op.drop_index(op.f('ix_answer_votes_answer_id'), table_name='answer_votes')
    op.drop_table('answer_votes')
    op.drop_index(op.f('ix_doubt_answers_doubt_id'), table_name='doubt_answers')
    op.drop_index(op.f('ix_doubt_answers_answered_by_id'), table_name='doubt_answers')
    op.drop_table('doubt_answers')
    op.drop_index(op.f('ix_doubts_subject_id'), table_name='doubts')
    op.drop_index(op.f('ix_doubts_status'), table_name='doubts')
    op.drop_index(op.f('ix_doubts_section_id'), table_name='doubts')
    op.drop_index(op.f('ix_doubts_asked_by_id'), table_name='doubts')
    op.drop_table('doubts')
    # ### end Alembic commands ###
